version: '2'

services:
  import-amz-shp:
    image: terrabrasilis/deter-sar-import-shp:v1.4.1
    container_name: import-amz-shp
    volumes:
      - /data/import_geojson:/data/files
      - /data/import_geojson/logs:/logs
      - /data/import_geojson/input:/input/files
    restart: always